apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-ns-resource-quota
spec:
   hard:
      pods: "7"
      replicationcontrollers: "10"
      requests.cpu: 1700m
      requests.memory: 1700Mi
      limits.cpu: 2000m
      limits.memory: 2000Mi
