apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:
  selector:
    app: active-mq
  ports:
    - name: http
      port: 8161
      nodePort: 30010

    - name: messages
      port: 61616

  type: NodePort

