apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:
  selector:
    app: active-mq
  ports:
    - name: http
      port: 8161
      nodePort: 30010

    - name: messages
      port: 61616

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: position-tracker

spec:
  selector:
    app: position-tracker
  ports:
    - name: http
      port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway

spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8080
      nodePort: 30020

  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: angular-webapp

spec:
  selector:
    app: angular-webapp
  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort