apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
    release: "1"
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1

---

apiVersion: v1
kind: Pod
metadata:
  name: queue-release2
  labels:
    app: queue
    release: "2"
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release2
