apiVersion: v1
kind: Pod
metadata:
  name: active-mq
  labels:
    app: active-mq
    release: "1"

spec:
  containers:
    - name: active-mq
      image: "richardchesterwood/k8s-fleetman-queue:release1"
      resources:
          requests:
            memory: "128Mi"
            cpu: "800m"
          limits:
            memory: "500Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Pod
metadata:
  name: active-mq
  labels:
    app: active-mq
    release: "2"

spec:
  containers:
    - name: active-mq
      image: "richardchesterwood/k8s-fleetman-queue:release2"
      resources:
          requests:
            memory: "128Mi"
            cpu: "800m"
          limits:
            memory: "500Mi"
            cpu: "1000m"